package com.example.backend.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import io.swagger.v3.oas.annotations.media.Schema;

@Document(collection = "categories")
@Data
@Schema(description = "Categories that posts can belong to")
public class Category implements GenericModel {
	@Id
	@Schema(description = "Unique identifier for the post, generated by the database.", example = "000000")
	private String id;
	@Schema(description = "The name given to the category.", example = "Music & Media")
	private String name;
	@Schema(description = "If it comes from an approved post")
    private boolean approved;   // true if it comes from an approved post

	public Category() {}

    public Category(String name) {
        this.name = name;
        this.approved = true;
    }
}