package com.example.backend.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.Instant;

import io.swagger.v3.oas.annotations.media.Schema;

@Document(collection = "comments")
@Data
@Schema(description = "Represents a comment on a post, which can be a top-level comment or a reply to another comment.")
public class Comment {
    @Id
	@JsonProperty(access = JsonProperty.Access.READ_ONLY)
	@Schema(description = "Unique identifier for the comment, generated by the database.", example = "000000")
    private String id;

	@Schema(description = "The ID of the post to which this comment belongs.", example = "000000")
    private String postId;       // reference to the Post
	@Schema(description = "The ID of the parent comment, null if this is a top-level comment.", example = "000000")
    private String parentId;     // null if top-level
	@Schema(description = "Anonymized username of the user who submitted this comment.", example = "anon wolf")
    private String author;       // submitted by the user
	@Schema(description = "The content of the comment.", example = "This is a comment.")
    private String content;
	@Schema(description = "The timestamp when the comment was created.", example = "2023-07-21T10:00:00Z")
    private Instant createdAt;
}