package com.example.backend.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.Instant;
import io.swagger.v3.oas.annotations.media.Schema;

@Document(collection = "suggestions")
@Data
@Schema(description = "Suggestion box that appears in a post, where users can submit additions or corrections to the post.")
public class Suggestion {
    @Id
	@Schema(description = "Unique identifier for the post, generated by the database.", example = "000000")
    private String id;

	@Schema(description = "Unique identifier for the post, generated by the database.", example = "000000")
    private String postId;
	@Schema(description = "Anonymized username of the user who submitted this suggestion. Or the admin.", example = "anon wolf")
    private String author;       // always "anon wolf" or admin
	@Schema(description = "The suggestion message", example = "This company also did this [], which I find terrible as well.")
    private String content;      // the suggestion text
	@Schema(description = "When the suggestion was made.")
    private Instant createdAt;
}