FROM node:22-alpine3.20
WORKDIR /app

# Update the Alpine base image to ensure the OS packages are patched
RUN apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Expose Angular dev server port
EXPOSE 4200

# Start the Angular development server with hot reload and proxy
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000", "--proxy-config", "proxy.conf.json"]