version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - ./db-data:/data/db
    networks:
      - internal-app-network

  backend:
    image: boycott-list-backend:latest   # use local image
    restart: unless-stopped
    container_name: backend_boycott_list
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/clientdb
    networks:
      - internal-app-network
      - proxy-network

  frontend:
    image: boycott-list-frontend:latest  # use local image
    restart: unless-stopped
    container_name: frontend_boycott_list
    ports:
      - "4200:4200"
    networks:
      - proxy-network
      - internal-app-network

networks:
  proxy-network:
    external: true
  internal-app-network:
    driver: bridge