import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  isMainModule,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';
import express from 'express';
import { join } from 'node:path';
import * as crypto from 'crypto';

const browserDistFolder = join(import.meta.dirname, '../browser');

const app = express();
const angularApp = new AngularNodeAppEngine();

/**
 * Serve static files from /browser
 */
app.use(
  express.static(browserDistFolder, {
    maxAge: '1y',
    index: false,
    redirect: false,
  }),
);

/**
 * Handle all other requests by rendering the Angular application.
 */
app.use((req, res, next) => {
  angularApp
    .handle(req)
    .then(async (response) => {
      if (!response) {
        return next();
      }

      // Generate a random 16-byte cryptographic nonce for THIS specific request
      const nonce = crypto.randomBytes(16).toString('base64');

      //Read the raw HTML generated by Angular
      let html = await response.text();

      // stamp the nonce into every <script> tag Angular created
      html = html.replace(/<script/g, `<script nonce="${nonce}"`);

      // create a new Web Response with the modified HTML and original headers/status
      const secureResponse = new Response(html, {
        status: response.status,
        statusText: response.statusText,
        headers: response.headers,
      });

      // attach the strict Content-Security-Policy header
	  secureResponse.headers.set(
      'Content-Security-Policy',
      `default-src 'self'; script-src 'self' 'nonce-${nonce}' 'unsafe-hashes' 'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com https://serif.com; img-src 'self' data:; connect-src 'self' http://localhost:8080 http://192.168.1.47:8080 https://api.lasignare.abdoudiallo.fr http://signare-backend:8080;`,
    );

      //  Let Angular's built-in helper send the secure response to the browser!
      writeResponseToNodeResponse(secureResponse, res);
    })
    .catch(next);
});

/**
 * Start the server if this module is the main entry point, or it is ran via PM2.
 * The server listens on the port defined by the `PORT` environment variable, or defaults to 4000.
 */
if (isMainModule(import.meta.url) || process.env['pm_id']) {
  const port = process.env['PORT'] || 4000;
  app.listen(Number(port), '0.0.0.0', () => {
    console.log(`Node Express server listening on http://0.0.0.0:${port}`);
    console.log(`Strict Content-Security-Policy with Nonce is ACTIVE.`);
  });
}

/**
 * Request handler used by the Angular CLI (for dev-server and during build) or Firebase Cloud Functions.
 */
export const reqHandler = createNodeRequestHandler(app);
